mingw-clangarm64:
	clang++ main.cpp ../glad/src/glad.c -o main -I ../glad/include -I C:/msys64/clangarm64/include/freetype2 -lglfw3 -lfreetype -lfreeimage -lopenal

macbrew:
	clang++ main.cpp ../glad/src/glad.c -o main -I ../glad/include -I /opt/homebrew/include -I /opt/homebrew/include/freetype2 -L /opt/homebrew/lib -lglfw -lfreetype -lfreeimage

dummy:
	