mingw-clangarm64:
	g++ main.cpp ../glad/src/glad.c -o main -I ../glad/include -I C:/msys64/clangarm64/include/freetype2 -lglfw3 -lfreetype -lfreeimage -lsfml-audio -std=c++17 -w

macbrew:
	g++ main.cpp ../glad/src/glad.c -o main -I ../glad/include -I /opt/homebrew/include -I /opt/homebrew/include/freetype2 -L /opt/homebrew/lib -lglfw -lfreetype -lfreeimage -lsfml-audio -lsfml-system -std=c++17

linux:
	clang++ main.cpp ../glad/src/glad.c -o main -I ../glad/include -I /usr/include/freetype2 -lglfw -lfreetype -lfreeimage -lsfml-audio -lsfml-system -std=c++17

dummy:
	
