windows-mingw:
	clang++ main.cpp -o main -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lglfw3 -lopengl32

macbrew:
	clang++ main.cpp -o main -I /opt/homebrew/include -L /opt/homebrew/lib -lSDL2 -lSDL2_image -lSDL2_ttf -lglfw3 -framework Cocoa -framework IOKit -framework OpenGL

dummy: